# -*- coding: utf-8 -*-
"""Assignment02Task05_21MIA1138ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZ9edy3keHCbHp-Ivxwo9D0T-3tEXp0g

# Mohamed Riyaz S
# 21MIA1138
# 04.08.2024
"""

pip install opencv-python-headless ffmpeg-python moviepy

import os
import subprocess
from moviepy.editor import ImageSequenceClip

# Define paths
video_path = "/content/istockphoto-186900953-640_adpp_is.mp4"
output_dir = "extracted_I_frames"
reconstructed_video_path = "reconstructed_video.mp4"
os.makedirs(output_dir, exist_ok=True)

# Extract I frames using ffmpeg
subprocess.run([
    "ffmpeg", "-i", video_path, "-vf",
    "select='eq(pict_type,I)',showinfo",
    "-vsync", "vfr", f"{output_dir}/I_frame_%03d.png"
])

# Gather extracted I frames
frame_files = sorted([os.path.join(output_dir, f) for f in os.listdir(output_dir) if f.startswith("I_frame")])

# Create a video from the extracted I frames
# Set the frame rate to a reduced value, e.g., 1 frame per second (fps)
frame_rate = 1
clip = ImageSequenceClip(frame_files, fps=frame_rate)
clip.write_videofile(reconstructed_video_path, codec="libx264")

print(f"Reconstructed video saved as {reconstructed_video_path}")