# -*- coding: utf-8 -*-
"""Assignment02Task01_21MIA1138.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7-rKa4HJl6RAqPrLkhrXJEbZ9R100il

# Mohamed Riyaz S
# 21MIA1138
# 04.08.2024
"""

!apt-get update
!apt-get install -y ffmpeg
!pip install ffmpeg-python

import ffmpeg

# Path to the uploaded video file
video_path = '/content/istockphoto-186900953-640_adpp_is.mp4'  # Adjust the path if necessary

# Probe the video to get information about its streams
probe = ffmpeg.probe(video_path)
video_info = None

# Extract information about the video stream
for stream in probe['streams']:
    if stream['codec_type'] == 'video':
        video_info = stream
        break

if video_info:
    print("Video Stream Information:")
    print(f"Width: {video_info['width']}")
    print(f"Height: {video_info['height']}")
    print(f"Frame Rate: {video_info['r_frame_rate']}")
    print(f"Duration: {video_info['duration']}")
    print(f"Number of Frames: {video_info['nb_frames']}")
else:
    print("No video stream found in the provided file.")

