# -*- coding: utf-8 -*-
"""Assignment02Task02_21MIA1138.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TenJVWOL4wCvracU90W0ZDbz_6NeFdbf

# Mohamed Riyaz S
# 21MIA1138
# 04.08.2024
"""

# Ensure the necessary libraries are installed
!pip install opencv-python-headless matplotlib

import cv2
import matplotlib.pyplot as plt

# Path to the uploaded video file
video_path = '/content/istockphoto-186900953-640_adpp_is.mp4'

# Initialize frame counters
i_frames = 0
p_frames = 0
b_frames = 0
total_frames = 0

# Open the video file
cap = cv2.VideoCapture(video_path)

# Check if the video file opened successfully
if not cap.isOpened():
    print("Error: Could not open video.")
else:
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Access frame type
        frame_type = int(cap.get(cv2.CAP_PROP_POS_FRAMES))
        total_frames += 1

        # Check the type of frame
        if frame_type == 1:  # I-frame
            i_frames += 1
        elif frame_type == 2:  # P-frame
            p_frames += 1
        elif frame_type == 3:  # B-frame
            b_frames += 1

    cap.release()

# Calculate the percentages
i_frame_percentage = (i_frames / total_frames) * 100
p_frame_percentage = (p_frames / total_frames) * 100
b_frame_percentage = (b_frames / total_frames) * 100

# Display results
print(f"Total frames: {total_frames}")
print(f"I-frames: {i_frames} ({i_frame_percentage:.2f}%)")
print(f"P-frames: {p_frames} ({p_frame_percentage:.2f}%)")
print(f"B-frames: {b_frames} ({b_frame_percentage:.2f}%)")

# Plotting the distribution of frame types
frame_types = ['I-frames', 'P-frames', 'B-frames']
frame_counts = [i_frames, p_frames, b_frames]
frame_percentages = [i_frame_percentage, p_frame_percentage, b_frame_percentage]

# Bar graph
plt.figure(figsize=(10, 5))
plt.bar(frame_types, frame_counts, color=['blue', 'orange', 'green'])
plt.title('Distribution of Frame Types in the Video')
plt.xlabel('Frame Types')
plt.ylabel('Count')
plt.show()

# Pie chart
plt.figure(figsize=(8, 8))
plt.pie(frame_percentages, labels=frame_types, autopct='%1.1f%%', colors=['blue', 'orange', 'green'])
plt.title('Percentage Distribution of Frame Types in the Video')
plt.show()